# Paramètres pour les modèles

# Modèle d'identification des cycles économiques
cycle_identification_model:
  type: "hidden_markov_model"
  n_states: 4  # Nombre d'états (expansion, pic, contraction, creux)
  n_iter: 100  # Nombre d'itérations
  random_state: 42
  indicators:
    - "gdp_growth"
    - "unemployment_rate"
    - "inflation_rate"
    - "industrial_production"
    - "yield_curve_spread"

# Classification des secteurs par cycle économique
sector_cycle_mapping:
  expansion:  # Croissance économique forte
    top_sectors:
      - "xlb"  # Matériaux
      - "xli"  # Industrie
      - "xly"  # Consommation discrétionnaire
      - "xlf"  # Finance
  peak:  # Fin de cycle de croissance, inflation en hausse
    top_sectors:
      - "xle"  # Énergie
      - "xlv"  # Santé
      - "xlp"  # Consommation de base
      - "xlre"  # Immobilier
  contraction:  # Récession, croissance négative
    top_sectors:
      - "xlu"  # Services publics
      - "xlv"  # Santé
      - "xlp"  # Consommation de base
      - "xlc"  # Services de communication
  trough:  # Début de reprise, taux d'intérêt bas
    top_sectors:
      - "xlk"  # Technologie
      - "xlf"  # Finance
      - "xli"  # Industrie
      - "xly"  # Consommation discrétionnaire

# Modèle de momentum sectoriel
momentum_model:
  type: "trend_following"
  lookback_periods: [1, 3, 6, 12]  # mois
  weights: [0.1, 0.2, 0.3, 0.4]  # Poids par période
  smoothing_factor: 0.1

# Modèle de pondération des secteurs
weighting_model:
  type: "mean_variance_optimization"
  risk_aversion: 1.0
  constraints:
    min_weight: 0.05
    max_weight: 0.4
    sector_correlation_penalty: 0.2